@startuml SurveyForm

actor User
participant SurveyForm
participant SurveyAMForm
participant SurveyPMForm
participant LoadData
participant HomePage

activate User
User -> SurveyForm: Form loads
activate SurveyForm
User -> SurveyForm: meridiemIndicator

alt meridiemIndicator == "am"
    SurveyForm -> SurveyAMForm: Load Form
    activate SurveyAMForm
    SurveyAMForm -> LoadData : 'http://127.0.0.1:8000/day-without-survey/', 'POST', { meridiemIndicator: "am" }
    activate LoadData
    LoadData --> SurveyAMForm: Days without associated SurveyAMForm
    deactivate LoadData
    SurveyAMForm --> User: Dates, questions
    User -> SurveyAMForm: Selected Date, question answers
    SurveyAMForm -> LoadData: Send Data to backend
    activate LoadData
    deactivate LoadData
    SurveyAMForm -> HomePage: get homepage
    deactivate SurveyAMForm
    activate HomePage
    HomePage --> User: redirect to homepage
    Deactivate HomePage

else meridiemIndicator == "pm"
    SurveyForm -> SurveyPMForm: Load Form
    activate SurveyPMForm
    SurveyPMForm -> LoadData : 'http://127.0.0.1:8000/day-without-survey/', 'POST', { meridiemIndicator: "pm" }
    activate LoadData
    LoadData --> SurveyPMForm: Days without associated SurveyPMForm
    deactivate LoadData
    SurveyPMForm --> User: Dates, questions
    User -> SurveyPMForm: Selected Date, question answers
    SurveyPMForm -> LoadData: Send Data to backend
    activate LoadData
    deactivate LoadData
    SurveyPMForm -> HomePage: get homepage
    deactivate SurveyPMForm
    activate HomePage
    HomePage --> User: redirect to homepage
    deactivate HomePage
    deactivate SurveyForm
end



@enduml