@startuml TimeSeriesGraphDay

actor User
participant DetermineTimeSpan
participant TimeSeriesGraphDay
participant processData
participant TimeConverter
participant getValue
participant KoreanTimeConverter
participant TimeSeriesLineChart

activate User
activate DetermineTimeSpan
DetermineTimeSpan -> TimeSeriesGraphDay : timeSeriesData , timeSpan, time_Config, type
Activate TimeSeriesGraphDay

TimeSeriesGraphDay -> processData : Start data processing
Activate processData
loop for i in length of timeSeriesData
    
    processData -> TimeConverter : Convert duration to minutes
    Activate TimeConverter
    TimeConverter --> processData : duration in minutes
    deactivate TimeConverter
    processData -> getValue : Get current value
    activate getValue
    getValue --> processData: Current value
    deactivate getValue
    

    processData -> KoreanTimeConverter : get timeStamp
    activate KoreanTimeConverter
    KoreanTimeConverter -> processData: timestamp
    deactivate KoreanTimeConverter
    processData -> processData: Create Point on time series graph
    
    processData -> getValue : Get next value
    activate getValue
    getValue --> processData: next value
    deactivate getValue
    
    
    loop while current value and next value are equavalent
        processData ->  processData: Iterate i
        processData -> getValue : Get next value
        activate getValue
        getValue --> processData: value
        deactivate getValue
    
    end
    
 
end

alt If value is consistant across the day
    processData -> KoreanTimeConverter : get last timeStamp
    activate KoreanTimeConverter
    KoreanTimeConverter -> processData: last timestamp
    deactivate KoreanTimeConverter
    processData -> processData:  Create Point on time series graph and end of day
end

processData --> TimeSeriesGraphDay: List of Points for time series visualisation
deactivate processData
TimeSeriesGraphDay -> TimeSeriesLineChart  : List of points
activate TimeSeriesLineChart 
deactivate TimeSeriesGraphDay
deactivate DetermineTimeSpan
TimeSeriesLineChart --> User : Visulaise Data
deactivate TimeSeriesLineChart

@enduml
